[package]
name = "platzi-curso-rust-basico"
version = "0.1.0"
authors = ["Yony Calsin <helloyonycalsin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
